# Generated by Django 4.2.25 on 2025-12-07 20:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('group', models.CharField(choices=[('REGULAR_INCOME', 'Renda principal'), ('EXTRA_INCOME', 'Renda extra'), ('SAVINGS', 'Poupança / Reserva'), ('INVESTMENT', 'Investimentos'), ('ESSENTIAL_EXPENSE', 'Despesas essenciais'), ('LIFESTYLE_EXPENSE', 'Estilo de vida'), ('GOAL', 'Metas e sonhos'), ('OTHER', 'Outros')], default='OTHER', max_length=24)),
                ('is_system_default', models.BooleanField(default=False, help_text='Categoria padrão do sistema (criada automaticamente para novos usuários)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário proprietário desta categoria (null = categoria global/padrão)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('reward_points', models.PositiveIntegerField(default=50)),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Média'), ('HARD', 'Difícil')], default='MEDIUM', max_length=8)),
                ('mission_type', models.CharField(choices=[('ONBOARDING', 'Primeiros Passos'), ('TPS_IMPROVEMENT', 'Aumentar Poupança (TPS)'), ('RDR_REDUCTION', 'Reduzir Gastos Recorrentes (RDR)'), ('ILI_BUILDING', 'Construir Reserva (ILI)'), ('CATEGORY_REDUCTION', 'Reduzir Gastos em Categoria')], default='ONBOARDING', help_text='Tipo de missão que determina quando será aplicada', max_length=30)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Ordem de prioridade para aplicação automática (menor = mais prioritário)')),
                ('target_tps', models.PositiveIntegerField(blank=True, help_text='TPS mínimo necessário (se aplicável)', null=True)),
                ('target_rdr', models.PositiveIntegerField(blank=True, help_text='RDR máximo permitido (se aplicável)', null=True)),
                ('min_ili', models.DecimalField(blank=True, decimal_places=1, help_text='ILI mínimo necessário', max_digits=4, null=True)),
                ('max_ili', models.DecimalField(blank=True, decimal_places=1, help_text='ILI máximo permitido', max_digits=4, null=True)),
                ('min_transactions', models.PositiveIntegerField(blank=True, help_text='Número mínimo de transações registradas para desbloquear esta missão', null=True)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_type', models.CharField(choices=[('TRANSACTION_COUNT', 'Registrar X Transações'), ('INDICATOR_THRESHOLD', 'Atingir Valor de Indicador'), ('CATEGORY_REDUCTION', 'Reduzir % em Categoria')], default='TRANSACTION_COUNT', help_text='Tipo de validação que determina como o progresso é calculado', max_length=35)),
                ('requires_consecutive_days', models.BooleanField(default=False, help_text='Se requer X dias CONSECUTIVOS atendendo critério')),
                ('min_consecutive_days', models.PositiveIntegerField(blank=True, help_text='Número mínimo de dias consecutivos', null=True)),
                ('target_reduction_percent', models.DecimalField(blank=True, decimal_places=2, help_text='% de redução alvo (ex: 15 = reduzir 15%)', max_digits=5, null=True)),
                ('category_spending_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Limite de gasto em reais para a categoria', max_digits=12, null=True)),
                ('savings_increase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor em R$ para aumentar poupança', max_digits=12, null=True)),
                ('requires_daily_action', models.BooleanField(default=False, help_text='Se requer ação diária (registrar transação, etc)')),
                ('min_daily_actions', models.PositiveIntegerField(blank=True, help_text='Número mínimo de ações diárias necessárias', null=True)),
                ('impacts', models.JSONField(blank=True, default=list, help_text='Lista de impactos ao completar (título, descrição, ícone, cor)')),
                ('tips', models.JSONField(blank=True, default=list, help_text='Lista de dicas contextuais (título, descrição, prioridade)')),
                ('min_transaction_frequency', models.PositiveIntegerField(blank=True, help_text='Frequência mínima de transações por semana (para missões de consistência)', null=True)),
                ('transaction_type_filter', models.CharField(choices=[('ALL', 'Todas'), ('INCOME', 'Receitas'), ('EXPENSE', 'Despesas'), ('TRANSFER', 'Transferências')], default='ALL', help_text='Tipo de transação a ser considerado na validação', max_length=10)),
                ('requires_payment_tracking', models.BooleanField(default=False, help_text='Se a missão requer rastreamento de pagamentos (campo is_paid nas transações)')),
                ('min_payments_count', models.PositiveIntegerField(blank=True, help_text='Número mínimo de pagamentos a serem rastreados', null=True)),
                ('is_system_generated', models.BooleanField(default=False, help_text='Se a missão foi gerada automaticamente pelo sistema')),
                ('generation_context', models.JSONField(blank=True, default=dict, help_text='Contexto de geração automática (dados usados para criar a missão)')),
                ('target_categories', models.ManyToManyField(blank=True, help_text='Categorias alvo para missões que envolvem múltiplas categorias', related_name='target_missions', to='finance.category')),
                ('target_category', models.ForeignKey(blank=True, help_text='Categoria alvo para missões de redução/limite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='finance.category')),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
                'ordering': ('priority', 'title'),
            },
        ),
        migrations.CreateModel(
            name='MissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('FAILED', 'Não Concluída'), ('SKIPPED', 'Pulada')], default='PENDING', max_length=10)),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('initial_tps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('initial_rdr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('initial_ili', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('initial_transaction_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_category_spending', models.DecimalField(blank=True, decimal_places=2, help_text='Gasto médio na categoria antes da missão começar', max_digits=12, null=True)),
                ('baseline_period_days', models.PositiveIntegerField(default=30, help_text='Número de dias usados para calcular baseline')),
                ('initial_savings_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total em poupança quando missão começou', max_digits=12, null=True)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Dias consecutivos atuais atendendo critério')),
                ('max_streak', models.PositiveIntegerField(default=0, help_text='Maior streak alcançado nesta missão')),
                ('days_met_criteria', models.PositiveIntegerField(default=0, help_text='Total de dias que atendeu critério (não necessariamente consecutivos)')),
                ('days_violated_criteria', models.PositiveIntegerField(default=0, help_text='Total de dias que violou critério')),
                ('last_violation_date', models.DateField(blank=True, help_text='Data da última violação de critério', null=True)),
                ('validation_details', models.JSONField(default=dict, help_text='Detalhes de como validação está sendo feita')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='finance.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Missão',
                'verbose_name_plural': 'Progressos de Missões',
                'ordering': ('mission__priority', 'mission__title'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('target_tps', models.PositiveIntegerField(default=15, help_text='meta básica de poupança em %')),
                ('target_rdr', models.PositiveIntegerField(default=35, help_text='meta de despesas recorrentes/renda em %')),
                ('target_ili', models.DecimalField(decimal_places=1, default=Decimal('6.0'), help_text='meta de liquidez imediata em meses', max_digits=4)),
                ('is_first_access', models.BooleanField(default=True, help_text='Indica se é o primeiro acesso do usuário (para onboarding)')),
                ('cached_tps', models.DecimalField(blank=True, decimal_places=2, help_text='TPS em cache', max_digits=6, null=True)),
                ('cached_rdr', models.DecimalField(blank=True, decimal_places=2, help_text='RDR em cache', max_digits=6, null=True)),
                ('cached_ili', models.DecimalField(blank=True, decimal_places=2, help_text='ILI em cache', max_digits=6, null=True)),
                ('cached_total_income', models.DecimalField(blank=True, decimal_places=2, help_text='Total de receitas em cache', max_digits=12, null=True)),
                ('cached_total_expense', models.DecimalField(blank=True, decimal_places=2, help_text='Total de despesas em cache', max_digits=12, null=True)),
                ('indicators_updated_at', models.DateTimeField(blank=True, help_text='Última atualização dos indicadores em cache', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], db_index=True, max_length=14)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_value', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_unit', models.CharField(blank=True, choices=[('DAYS', 'Dias'), ('WEEKS', 'Semanas'), ('MONTHS', 'Meses')], max_length=10, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_DEACTIVATED', 'Usuário Desativado'), ('USER_REACTIVATED', 'Usuário Reativado'), ('XP_ADJUSTED', 'XP Ajustado'), ('LEVEL_ADJUSTED', 'Nível Ajustado'), ('PROFILE_UPDATED', 'Perfil Atualizado'), ('MISSIONS_RESET', 'Missões Resetadas'), ('TRANSACTIONS_DELETED', 'Transações Deletadas'), ('OTHER', 'Outro')], help_text='Tipo de ação realizada', max_length=30)),
                ('old_value', models.TextField(blank=True, help_text='Valor anterior (JSON se necessário)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Novo valor (JSON se necessário)', null=True)),
                ('reason', models.TextField(blank=True, help_text='Motivo/justificativa da ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do administrador', null=True)),
                ('admin_user', models.ForeignKey(help_text='Administrador que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='Usuário que recebeu a ação', on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Ação Administrativa',
                'verbose_name_plural': 'Logs de Ações Administrativas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveIntegerField(help_text='Quantidade de XP concedida')),
                ('level_before', models.PositiveIntegerField(help_text='Nível do usuário antes da recompensa')),
                ('level_after', models.PositiveIntegerField(help_text='Nível do usuário após a recompensa')),
                ('xp_before', models.PositiveIntegerField(help_text='XP do usuário antes da recompensa')),
                ('xp_after', models.PositiveIntegerField(help_text='XP do usuário após a recompensa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='finance.missionprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação de XP',
                'verbose_name_plural': 'Transações de XP',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='finance_xpt_user_id_88f77f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False)),
                ('source_transaction_uuid', models.UUIDField(db_index=True, help_text='UUID da transação de origem (normalmente uma receita)')),
                ('target_transaction_uuid', models.UUIDField(db_index=True, help_text='UUID da transação de destino (normalmente uma dívida)')),
                ('linked_amount', models.DecimalField(decimal_places=2, help_text='Valor que está sendo transferido/vinculado', max_digits=12)),
                ('link_type', models.CharField(choices=[('EXPENSE_PAYMENT', 'Pagamento de despesa'), ('INTERNAL_TRANSFER', 'Transferência interna'), ('SAVINGS_ALLOCATION', 'Alocação para poupança')], default='EXPENSE_PAYMENT', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Descrição opcional da vinculação', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Se True, vincular automaticamente transações recorrentes futuras')),
                ('user', models.ForeignKey(help_text='Usuário proprietário da vinculação', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo de Transação',
                'verbose_name_plural': 'Vínculos de Transações',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='finance_tra_user_id_0560eb_idx'), models.Index(fields=['source_transaction_uuid'], name='finance_tra_source__4fb083_idx'), models.Index(fields=['target_transaction_uuid'], name='finance_tra_target__2b7f07_idx'), models.Index(fields=['user', 'source_transaction_uuid'], name='trl_user_src_uuid_idx'), models.Index(fields=['user', 'target_transaction_uuid'], name='trl_user_tgt_uuid_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transactionlink',
            constraint=models.CheckConstraint(check=models.Q(('linked_amount__gt', 0)), name='linked_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='finance_tra_user_id_35643f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='finance_tra_user_id_be5f56_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date', '-created_at'], name='finance_tra_user_id_6e1507_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'deleted_at'], name='finance_tra_user_id_9468a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionprogress',
            unique_together={('user', 'mission')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='finance_cat_user_id_0d1be8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'is_system_default'], name='finance_cat_user_id_e0ad5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'type')},
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['-timestamp'], name='finance_adm_timesta_99055d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['target_user', '-timestamp'], name='finance_adm_target__a4ba93_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['admin_user', '-timestamp'], name='finance_adm_admin_u_8d9daf_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='finance_adm_action__40bdb7_idx'),
        ),
    ]
