# Generated by Django 4.2.25 on 2025-12-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='target_reduction_percent',
        ),
        migrations.AddField(
            model_name='mission',
            name='target_percentage_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% de mudança alvo (ex: 15 = aumentar/reduzir 15% dependendo do tipo de transação)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='transaction_type_filter',
            field=models.CharField(choices=[('ALL', 'Todas'), ('INCOME', 'Receitas'), ('EXPENSE', 'Despesas'), ('PAYMENT', 'Pagamentos'), ('DEPOSIT', 'Aportes')], default='ALL', help_text='Tipo de transação a ser considerado na validação', max_length=10),
        ),
        migrations.AlterField(
            model_name='mission',
            name='validation_type',
            field=models.CharField(choices=[('TRANSACTION_COUNT', 'Registrar X Transações'), ('INDICATOR_THRESHOLD', 'Atingir Valor de Indicador'), ('CATEGORY_REDUCTION', 'Reduzir % em Categoria'), ('SAVINGS_INCREASE', 'Aumentar Poupança')], default='TRANSACTION_COUNT', help_text='Tipo de validação que determina como o progresso é calculado', max_length=35),
        ),
    ]
