# Generated by Django 4.2.26 on 2025-12-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='validation_type',
            field=models.CharField(choices=[('TRANSACTION_COUNT', 'Registrar X Transações'), ('INDICATOR_THRESHOLD', 'Atingir Valor de Indicador'), ('CATEGORY_REDUCTION', 'Reduzir % em Categoria'), ('SAVINGS_INCREASE', 'Aumentar Poupança')], default='TRANSACTION_COUNT', help_text='Tipo de validação que determina como o progresso é calculado', max_length=35),
        ),
    ]
