# Generated by ChatGPT on 2025-10-31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_seed_missions"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="group",
            field=models.CharField(
                choices=[
                    ("REGULAR_INCOME", "Renda principal"),
                    ("EXTRA_INCOME", "Renda extra"),
                    ("SAVINGS", "Poupança / Reserva"),
                    ("INVESTMENT", "Investimentos"),
                    ("ESSENTIAL_EXPENSE", "Despesas essenciais"),
                    ("LIFESTYLE_EXPENSE", "Estilo de vida"),
                    ("DEBT", "Dívidas"),
                    ("GOAL", "Metas e sonhos"),
                    ("OTHER", "Outros"),
                ],
                default="OTHER",
                max_length=24,
            ),
        ),
    ]
