# Generated by Django 4.2.25 on 2025-11-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category_group'),
        ('finance', '0003_transaction_recurrence'),
    ]

    operations = [
    ]
