# Generated by Django 4.2.25 on 2025-11-01 15:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_merge_0003_category_group_0003_transaction_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='max_ili',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='min_ili',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_ili',
            field=models.DecimalField(decimal_places=1, default=Decimal('6.0'), help_text='meta de liquidez imediata em meses', max_digits=4),
        ),
    ]
