# Generated by Django 4.2.25 on 2025-11-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_add_transaction_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cached_total_debt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de dívidas em cache', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cached_total_expense',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de despesas em cache', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cached_total_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de receitas em cache', max_digits=12, null=True),
        ),
    ]
