# Generated by manual improvement on 2025-11-03
from django.db import migrations


def create_default_categories(apps, schema_editor):
    """
    Cria categorias padrão do sistema com grupos apropriados.
    Estas categorias servem como base para todos os usuários.
    """
    Category = apps.get_model("finance", "Category")
    
    # Limpar categorias padrão antigas (user=None)
    Category.objects.filter(user__isnull=True).delete()
    
    # Categorias padrão do sistema (user=None)
    default_categories = [
        # ===== RECEITAS =====
        # Renda Principal
        {
            "name": "Salário",
            "type": "INCOME",
            "group": "REGULAR_INCOME",
            "color": "#4CAF50",
        },
        {
            "name": "Pensão",
            "type": "INCOME",
            "group": "REGULAR_INCOME",
            "color": "#66BB6A",
        },
        {
            "name": "Aposentadoria",
            "type": "INCOME",
            "group": "REGULAR_INCOME",
            "color": "#81C784",
        },
        
        # Renda Extra
        {
            "name": "Freela",
            "type": "INCOME",
            "group": "EXTRA_INCOME",
            "color": "#9CCC65",
        },
        {
            "name": "Bico",
            "type": "INCOME",
            "group": "EXTRA_INCOME",
            "color": "#AED581",
        },
        {
            "name": "Venda",
            "type": "INCOME",
            "group": "EXTRA_INCOME",
            "color": "#C5E1A5",
        },
        {
            "name": "Prêmio",
            "type": "INCOME",
            "group": "EXTRA_INCOME",
            "color": "#DCE775",
        },
        
        # Investimentos e Poupança
        {
            "name": "Rendimento Investimento",
            "type": "INCOME",
            "group": "INVESTMENT",
            "color": "#FDD835",
        },
        {
            "name": "Dividendos",
            "type": "INCOME",
            "group": "INVESTMENT",
            "color": "#FFEB3B",
        },
        {
            "name": "Resgate Investimento",
            "type": "INCOME",
            "group": "INVESTMENT",
            "color": "#FFF176",
        },
        
        # Outros
        {
            "name": "Restituição",
            "type": "INCOME",
            "group": "OTHER",
            "color": "#B0BEC5",
        },
        {
            "name": "Outros ganhos",
            "type": "INCOME",
            "group": "OTHER",
            "color": "#CFD8DC",
        },
        
        # ===== DESPESAS =====
        # Despesas Essenciais
        {
            "name": "Moradia",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#F44336",
        },
        {
            "name": "Aluguel",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#EF5350",
        },
        {
            "name": "Condomínio",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#E57373",
        },
        {
            "name": "Luz",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#EF9A9A",
        },
        {
            "name": "Água",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#2196F3",
        },
        {
            "name": "Gás",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#FFAB91",
        },
        {
            "name": "Internet",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#64B5F6",
        },
        {
            "name": "Telefone",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#42A5F5",
        },
        {
            "name": "Alimentação",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#FF9800",
        },
        {
            "name": "Mercado",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#FFB74D",
        },
        {
            "name": "Transporte",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#9C27B0",
        },
        {
            "name": "Combustível",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#AB47BC",
        },
        {
            "name": "Transporte público",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#BA68C8",
        },
        {
            "name": "Saúde",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#E91E63",
        },
        {
            "name": "Plano de saúde",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#EC407A",
        },
        {
            "name": "Remédios",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#F06292",
        },
        {
            "name": "Educação",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#3F51B5",
        },
        {
            "name": "Mensalidade escolar",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#5C6BC0",
        },
        {
            "name": "Material escolar",
            "type": "EXPENSE",
            "group": "ESSENTIAL_EXPENSE",
            "color": "#7986CB",
        },
        
        # Estilo de Vida
        {
            "name": "Lazer",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#00BCD4",
        },
        {
            "name": "Restaurante",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#26C6DA",
        },
        {
            "name": "Cinema",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#4DD0E1",
        },
        {
            "name": "Streaming",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#80DEEA",
        },
        {
            "name": "Academia",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#4DB6AC",
        },
        {
            "name": "Viagem",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#009688",
        },
        {
            "name": "Roupas",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#E1BEE7",
        },
        {
            "name": "Beleza",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#CE93D8",
        },
        {
            "name": "Pet",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#BCAAA4",
        },
        {
            "name": "Presente",
            "type": "EXPENSE",
            "group": "LIFESTYLE_EXPENSE",
            "color": "#FF6F00",
        },
        
        # Poupança e Reserva
        # IMPORTANTE: Estas categorias são do tipo INCOME (não EXPENSE)
        # Quando o usuário GUARDA dinheiro, registra como INCOME em "Reserva de Emergência"
        # Quando o usuário RESGATA dinheiro, registra como EXPENSE em "Reserva de Emergência"
        # Isso permite:
        # 1. Calcular TPS corretamente (poupança não conta como despesa)
        # 2. Rastrear aportes vs resgates
        # 3. Calcular saldo da reserva = INCOME (aportes) - EXPENSE (resgates)
        {
            "name": "Reserva de Emergência",
            "type": "INCOME",
            "group": "SAVINGS",
            "color": "#8BC34A",
        },
        {
            "name": "Poupança",
            "type": "INCOME",
            "group": "SAVINGS",
            "color": "#9CCC65",
        },
        
        # Investimentos
        {
            "name": "Investimento",
            "type": "EXPENSE",
            "group": "INVESTMENT",
            "color": "#FFC107",
        },
        {
            "name": "Ações",
            "type": "EXPENSE",
            "group": "INVESTMENT",
            "color": "#FFD54F",
        },
        {
            "name": "Fundos",
            "type": "EXPENSE",
            "group": "INVESTMENT",
            "color": "#FFE082",
        },
        {
            "name": "Tesouro Direto",
            "type": "EXPENSE",
            "group": "INVESTMENT",
            "color": "#FFECB3",
        },
        {
            "name": "Previdência",
            "type": "EXPENSE",
            "group": "INVESTMENT",
            "color": "#FFF9C4",
        },
        
        # Metas e Sonhos
        {
            "name": "Meta Casa",
            "type": "EXPENSE",
            "group": "GOAL",
            "color": "#795548",
        },
        {
            "name": "Meta Carro",
            "type": "EXPENSE",
            "group": "GOAL",
            "color": "#8D6E63",
        },
        {
            "name": "Meta Viagem",
            "type": "EXPENSE",
            "group": "GOAL",
            "color": "#A1887F",
        },
        {
            "name": "Meta Casamento",
            "type": "EXPENSE",
            "group": "GOAL",
            "color": "#D7CCC8",
        },
        
        # Outros
        {
            "name": "Outros gastos",
            "type": "EXPENSE",
            "group": "OTHER",
            "color": "#90A4AE",
        },
        {
            "name": "Imposto",
            "type": "EXPENSE",
            "group": "OTHER",
            "color": "#78909C",
        },
        
        # ===== DÍVIDAS =====
        {
            "name": "Cartão de Crédito",
            "type": "DEBT",
            "group": "DEBT",
            "color": "#D32F2F",
        },
        {
            "name": "Empréstimo Pessoal",
            "type": "DEBT",
            "group": "DEBT",
            "color": "#C62828",
        },
        {
            "name": "Financiamento Carro",
            "type": "DEBT",
            "group": "DEBT",
            "color": "#B71C1C",
        },
        {
            "name": "Financiamento Casa",
            "type": "DEBT",
            "group": "DEBT",
            "color": "#F44336",
        },
        {
            "name": "Empréstimo Consignado",
            "type": "DEBT",
            "group": "DEBT",
            "color": "#E53935",
        },
        {
            "name": "Cheque Especial",
            "type": "DEBT",
            "group": "DEBT",
            "color": "#EF5350",
        },
        {
            "name": "Outras Dívidas",
            "type": "DEBT",
            "group": "DEBT",
            "color": "#E57373",
        },
    ]
    
    for cat_data in default_categories:
        Category.objects.create(
            name=cat_data["name"],
            type=cat_data["type"],
            group=cat_data["group"],
            color=cat_data["color"],
            user=None,  # Categoria do sistema
        )


def reverse_default_categories(apps, schema_editor):
    """Remove categorias padrão do sistema."""
    Category = apps.get_model("finance", "Category")
    Category.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_fix_mission_progress_initial_values"),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
