# Generated by manual improvement on 2025-11-03
from decimal import Decimal
from django.db import migrations


def update_mission_descriptions(apps, schema_editor):
    """
    Atualiza descrições das missões para serem mais claras sobre
    como as categorias e grupos devem ser usados.
    """
    Mission = apps.get_model("finance", "Mission")
    
    # Atualizar missões existentes com descrições mais claras
    mission_updates = {
        "Primeiros passos": {
            "description": "Registre suas primeiras 5 transações incluindo receitas (salário, freelas) e despesas (alimentação, transporte). Use as categorias corretas para cada tipo de gasto.",
        },
        "Mapeamento inicial": {
            "description": "Cadastre 10 transações variadas incluindo receitas regulares e extras, despesas essenciais (moradia, alimentação) e de estilo de vida (lazer). Categorize corretamente para análise precisa.",
        },
        "Registro completo": {
            "description": "Alcance 20 transações bem categorizadas. Inclua receitas, despesas essenciais (luz, água, transporte), despesas de estilo de vida e, se aplicável, pagamentos de dívidas.",
        },
        "Começar a poupar": {
            "description": "Melhore sua taxa de poupança para 10% registrando aportes na categoria 'Poupança' ou 'Reserva de Emergência' como DESPESA. Reduza gastos nas categorias de estilo de vida (lazer, restaurantes).",
        },
        "Disciplina financeira": {
            "description": "Alcance 15% de poupança aumentando aportes mensais em categorias do grupo SAVINGS (Poupança, Reserva de Emergência). Controle despesas de estilo de vida e mantenha receitas estáveis.",
        },
        "Poupador consistente": {
            "description": "Mantenha 20% de poupança com aportes regulares em categorias de investimento e reserva. Revise despesas não essenciais e otimize gastos nas categorias de estilo de vida.",
        },
        "Controle das dívidas": {
            "description": "Reduza dívidas para menos de 49% da renda registrando pagamentos como DEBT_PAYMENT nas categorias de dívida (Cartão, Empréstimo). Evite novos gastos a crédito.",
        },
        "Respirar melhor": {
            "description": "Baixe comprometimento para 42% acelerando pagamentos de dívidas. Use DEBT_PAYMENT para registrar amortizações nas categorias de Cartão de Crédito, Empréstimos e Financiamentos.",
        },
        "Dívidas sob controle": {
            "description": "Alcance comprometimento abaixo de 35% quitando ou renegociando dívidas. Registre todos os pagamentos como DEBT_PAYMENT nas categorias corretas (Cartão, Empréstimo, Financiamento).",
        },
        "Primeira segurança": {
            "description": "Construa reserva que cubra 1 mês de despesas essenciais fazendo aportes mensais na categoria 'Reserva de Emergência' como DESPESA. Foque em proteger gastos com moradia, alimentação e transporte.",
        },
        "Almofada de segurança": {
            "description": "Amplie reserva para 3 meses de despesas essenciais aumentando aportes em 'Reserva de Emergência'. Calcule suas despesas médias em categorias essenciais (moradia, alimentação, transporte, saúde).",
        },
        "Reserva sólida": {
            "description": "Complete reserva de 6 meses de despesas essenciais com aportes consistentes. Use categoria 'Reserva de Emergência' para aportes e mantenha separado de outras economias e investimentos.",
        },
        "Diversificar investimentos": {
            "description": "Com reserva consolidada, explore investimentos registrando aportes em categorias do grupo INVESTMENT (Ações, Fundos, Tesouro Direto). Mantenha disciplina de poupança e controle de dívidas.",
        },
        "Otimização patrimonial": {
            "description": "Maximize investimentos de longo prazo usando categorias de investimento (Ações, Fundos, Previdência) enquanto mantém índices saudáveis. Balance entre liquidez, segurança e rentabilidade.",
        },
    }
    
    for title, updates in mission_updates.items():
        try:
            mission = Mission.objects.get(title=title)
            for field, value in updates.items():
                setattr(mission, field, value)
            mission.save()
        except Mission.DoesNotExist:
            pass


def reverse_mission_descriptions(apps, schema_editor):
    """Não precisa reverter - descrições antigas não são críticas."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_improved_categories_system"),
    ]

    operations = [
        migrations.RunPython(update_mission_descriptions, reverse_mission_descriptions),
    ]
