# Generated by Django 4.2.25 on 2025-11-04 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0013_update_mission_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveIntegerField(help_text='Quantidade de XP concedida')),
                ('level_before', models.PositiveIntegerField(help_text='Nível do usuário antes da recompensa')),
                ('level_after', models.PositiveIntegerField(help_text='Nível do usuário após a recompensa')),
                ('xp_before', models.PositiveIntegerField(help_text='XP do usuário antes da recompensa')),
                ('xp_after', models.PositiveIntegerField(help_text='XP do usuário após a recompensa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='finance.missionprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='finance_xpt_user_id_88f77f_idx')],
            },
        ),
    ]
