# Generated by Django 4.2.25 on 2025-11-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0016_recalculate_indicators_with_correct_formulas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_amount', models.DecimalField(decimal_places=2, help_text='Valor que está sendo transferido/vinculado', max_digits=12)),
                ('link_type', models.CharField(choices=[('DEBT_PAYMENT', 'Pagamento de dívida'), ('INTERNAL_TRANSFER', 'Transferência interna'), ('SAVINGS_ALLOCATION', 'Alocação para poupança')], default='DEBT_PAYMENT', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Descrição opcional da vinculação', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Se True, vincular automaticamente transações recorrentes futuras')),
                ('source_transaction', models.ForeignKey(help_text='Transação de origem (normalmente uma receita)', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='finance.transaction')),
                ('target_transaction', models.ForeignKey(help_text='Transação de destino (normalmente uma dívida)', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='finance.transaction')),
                ('user', models.ForeignKey(help_text='Usuário proprietário da vinculação', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='finance_tra_user_id_0560eb_idx'), models.Index(fields=['source_transaction'], name='finance_tra_source__31780a_idx'), models.Index(fields=['target_transaction'], name='finance_tra_target__b63973_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transactionlink',
            constraint=models.CheckConstraint(check=models.Q(('linked_amount__gt', 0)), name='linked_amount_positive'),
        ),
    ]
