# Generated by Django 4.2.25 on 2025-11-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_transactionlink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='goal',
            name='auto_update',
            field=models.BooleanField(default=False, help_text='Atualizar automaticamente com base nas transações'),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('SAVINGS', 'Juntar Dinheiro'), ('CATEGORY_EXPENSE', 'Reduzir Gastos'), ('CATEGORY_INCOME', 'Aumentar Receita'), ('DEBT_REDUCTION', 'Reduzir Dívidas'), ('CUSTOM', 'Personalizada')], default='CUSTOM', help_text='Tipo da meta', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_reduction_goal',
            field=models.BooleanField(default=False, help_text='True se o objetivo é reduzir (gastos/dívidas)'),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_category',
            field=models.ForeignKey(blank=True, help_text='Categoria vinculada (para metas CATEGORY_*)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='finance.category'),
        ),
        migrations.AddField(
            model_name='goal',
            name='tracking_period',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('TOTAL', 'Total')], default='TOTAL', help_text='Período de rastreamento', max_length=10),
        ),
    ]
