# Generated by Django 4.2.25 on 2025-11-05 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0020_goal_initial_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('REJECTED', 'Rejeitado')], default='PENDING', help_text='Status da solicitação de amizade', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da solicitação')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Data em que a solicitação foi aceita', null=True)),
                ('friend', models.ForeignKey(help_text='Usuário que recebeu a solicitação de amizade', on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuário que enviou a solicitação de amizade', on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='finance_fri_user_id_d9d110_idx'), models.Index(fields=['friend', 'status'], name='finance_fri_friend__d29006_idx'), models.Index(fields=['status', '-created_at'], name='finance_fri_status_d40dff_idx')],
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
