# Generated by Django 4.2.25 on 2025-11-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_add_security_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goal',
            name='goal_target_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='goal',
            name='goal_current_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_recurrence_fields_required',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_user_id_6e1507_idx',
            old_name='finance_tra_user_da_idx',
        ),
        migrations.AddField(
            model_name='friendship',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, help_text='Identificador único universal (substituirá o ID numérico)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, help_text='Identificador único universal (substituirá o ID numérico)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, help_text='Identificador único universal (substituirá o ID numérico)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transactionlink',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, help_text='Identificador único universal (substituirá o ID numérico)', null=True, unique=True),
        ),
    ]
