# Generated by Django 4.2.25 on 2025-11-06 01:23
# Fix Many-to-Many table to use UUID foreign key for Goal

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_convert_to_uuid_pk_safe'),
    ]

    operations = [
        # A tabela M2M finance_goal_tracked_categories tem goal_id como bigint
        # Precisamos recriá-la com goal_id como UUID
        
        # Salvar dados existentes
        migrations.RunSQL(
            sql='''
                CREATE TABLE IF NOT EXISTS finance_goal_tracked_categories_backup AS 
                SELECT * FROM finance_goal_tracked_categories;
            ''',
            reverse_sql='DROP TABLE IF EXISTS finance_goal_tracked_categories_backup;'
        ),
        
        # Dropar tabela antiga
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS finance_goal_tracked_categories CASCADE;',
            reverse_sql='SELECT 1;'  # Irreversível - backup existe
        ),
        
        # Django vai recriar automaticamente no próximo makemigrations
        # com o tipo correto (UUID)
    ]
