# Generated by Django 4.2.25 on 2025-11-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_fix_goal_m2m_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='id',
            field=models.UUIDField(default=None, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=None, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=None, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionlink',
            name='id',
            field=models.UUIDField(default=None, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionlink',
            name='source_transaction_uuid',
            field=models.UUIDField(db_index=True, help_text='UUID da transação de origem (normalmente uma receita)'),
        ),
        migrations.AlterField(
            model_name='transactionlink',
            name='target_transaction_uuid',
            field=models.UUIDField(db_index=True, help_text='UUID da transação de destino (normalmente uma dívida)'),
        ),
    ]
