# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


def migrate_global_categories_to_users(apps, schema_editor):
    """
    Migra categorias globais (user=None) para cada usuário existente.
    Cada usuário recebe uma cópia das categorias padrão.
    """
    Category = apps.get_model('finance', 'Category')
    User = apps.get_model('auth', 'User')
    
    # Buscar categorias sem dono (globais)
    global_categories = Category.objects.filter(user__isnull=True)
    
    if not global_categories.exists():
        print("Nenhuma categoria global encontrada. Pulando migração.")
        return
    
    print(f"Encontradas {global_categories.count()} categorias globais.")
    
    # Para cada usuário, criar cópias das categorias globais
    users = User.objects.all()
    total_created = 0
    
    for user in users:
        for category in global_categories:
            # Verificar se já existe categoria com mesmo nome e tipo
            exists = Category.objects.filter(
                user=user,
                name=category.name,
                type=category.type
            ).exists()
            
            if not exists:
                Category.objects.create(
                    user=user,
                    name=category.name,
                    type=category.type,
                    color=category.color,
                    group=category.group,
                    is_system_default=True,
                )
                total_created += 1
    
    print(f"Criadas {total_created} categorias personalizadas para {users.count()} usuários.")
    
    # Deletar categorias globais antigas
    deleted_count = global_categories.count()
    global_categories.delete()
    print(f"Deletadas {deleted_count} categorias globais.")


def reverse_migration(apps, schema_editor):
    """
    Reversão: deleta categorias marcadas como system_default
    e recria algumas categorias globais básicas.
    """
    Category = apps.get_model('finance', 'Category')
    
    # Deletar categorias de sistema
    Category.objects.filter(is_system_default=True).delete()
    
    # Recriar algumas categorias globais básicas
    default_categories = [
        {'name': 'Salário', 'type': 'INCOME', 'group': 'REGULAR_INCOME', 'color': '#4CAF50'},
        {'name': 'Alimentação', 'type': 'EXPENSE', 'group': 'ESSENTIAL_EXPENSE', 'color': '#FF9800'},
        {'name': 'Transporte', 'type': 'EXPENSE', 'group': 'ESSENTIAL_EXPENSE', 'color': '#2196F3'},
    ]
    
    for cat_data in default_categories:
        Category.objects.create(
            user=None,
            is_system_default=False,
            **cat_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_create_m2m_table_with_uuid'),
    ]

    operations = [
        # 1. Adicionar campo is_system_default
        migrations.AddField(
            model_name='category',
            name='is_system_default',
            field=models.BooleanField(
                default=False,
                help_text='Categoria padrão do sistema (somente leitura para usuários)'
            ),
        ),
        
        # 2. Migrar categorias globais para cada usuário
        migrations.RunPython(
            migrate_global_categories_to_users,
            reverse_code=reverse_migration
        ),
    ]
