# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_isolate_categories'),
    ]

    operations = [
        # 1. Tornar campo user obrigatório (NOT NULL)
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categories',
                to='auth.user',
                help_text='Usuário proprietário desta categoria',
            ),
        ),
        
        # 2. Adicionar índice para melhor performance
        migrations.AddIndex(
            model_name='category',
            index=models.Index(
                fields=['user', 'type', 'is_system_default'],
                name='cat_user_type_sys_idx'
            ),
        ),
    ]
