# Generated by Django 4.2.25 on 2025-11-09 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0036_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('tps_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rdr_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ili_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category_spending', models.DecimalField(blank=True, decimal_places=2, help_text='Gasto na categoria alvo neste dia/período', max_digits=12, null=True)),
                ('goal_progress', models.DecimalField(blank=True, decimal_places=2, help_text='% de progresso da meta neste dia', max_digits=5, null=True)),
                ('goal_current_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('savings_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total em poupança neste dia', max_digits=12, null=True)),
                ('met_criteria', models.BooleanField(default=False, help_text='Se atendeu os critérios da missão neste dia')),
                ('criteria_details', models.JSONField(default=dict, help_text='Detalhes de quais critérios foram atendidos')),
                ('consecutive_days_met', models.PositiveIntegerField(default=0, help_text='Quantos dias consecutivos atendeu critério até hoje')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='UserDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Data do snapshot (YYYY-MM-DD)')),
                ('tps', models.DecimalField(decimal_places=2, help_text='Taxa de Poupança Pessoal do dia (%)', max_digits=6)),
                ('rdr', models.DecimalField(decimal_places=2, help_text='Razão Dívida-Receita do dia (%)', max_digits=6)),
                ('ili', models.DecimalField(decimal_places=2, help_text='Índice de Liquidez Imediata (meses)', max_digits=6)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Total de receitas (acumulado do mês)', max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, help_text='Total de despesas (acumulado do mês)', max_digits=12)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, help_text='Total de dívidas', max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo disponível (receitas - despesas - dívidas)', max_digits=12)),
                ('category_spending', models.JSONField(default=dict, help_text='Gastos por categoria no mês atual até esta data')),
                ('savings_added_today', models.DecimalField(decimal_places=2, default=0, help_text='Valor adicionado a poupança/investimentos hoje', max_digits=12)),
                ('savings_total', models.DecimalField(decimal_places=2, default=0, help_text='Total acumulado em poupança/investimentos', max_digits=12)),
                ('goals_progress', models.JSONField(default=dict, help_text='Progresso de cada meta ativa')),
                ('transactions_registered_today', models.BooleanField(default=False, help_text='Se registrou pelo menos 1 transação hoje')),
                ('transaction_count_today', models.PositiveIntegerField(default=0, help_text='Número de transações registradas hoje')),
                ('total_transactions_lifetime', models.PositiveIntegerField(default=0, help_text='Total de transações desde sempre')),
                ('budget_exceeded', models.BooleanField(default=False, help_text='Se excedeu orçamento em alguma categoria hoje')),
                ('budget_violations', models.JSONField(default=list, help_text='Categorias que excederam orçamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='UserMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('avg_tps', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_rdr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_ili', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('top_category', models.CharField(blank=True, max_length=100)),
                ('top_category_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category_spending', models.JSONField(default=dict)),
                ('days_with_transactions', models.PositiveIntegerField(default=0, help_text='Quantos dias do mês registrou transações')),
                ('days_in_month', models.PositiveIntegerField(default=30)),
                ('consistency_rate', models.DecimalField(decimal_places=2, help_text='% de dias com registro (days_with_transactions / days_in_month)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='goal_user_deadline_idx',
        ),
        migrations.RemoveIndex(
            model_name='missionprogress',
            name='mission_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tx_user_date_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tx_user_cat_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transactionlink',
            name='txlink_user_type_idx',
        ),
        migrations.AddField(
            model_name='mission',
            name='category_spending_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite de gasto em reais para a categoria', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='goal_progress_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% de progresso alvo na meta (ex: 80 = completar 80%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='min_consecutive_days',
            field=models.PositiveIntegerField(blank=True, help_text='Número mínimo de dias consecutivos', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='min_daily_actions',
            field=models.PositiveIntegerField(blank=True, help_text='Número mínimo de ações diárias necessárias', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='requires_consecutive_days',
            field=models.BooleanField(default=False, help_text='Se requer X dias CONSECUTIVOS atendendo critério'),
        ),
        migrations.AddField(
            model_name='mission',
            name='requires_daily_action',
            field=models.BooleanField(default=False, help_text='Se requer ação diária (registrar transação, etc)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='savings_increase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor em R$ para aumentar poupança', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_category',
            field=models.ForeignKey(blank=True, help_text='Categoria alvo para missões de redução/limite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='finance.category'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_goal',
            field=models.ForeignKey(blank=True, help_text='Meta alvo (se missão for sobre meta específica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='finance.goal'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_reduction_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% de redução alvo (ex: 15 = reduzir 15%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='validation_type',
            field=models.CharField(choices=[('SNAPSHOT', 'Comparação pontual (inicial vs atual)'), ('TEMPORAL', 'Manter critério por período'), ('CATEGORY_REDUCTION', 'Reduzir gasto em categoria'), ('CATEGORY_LIMIT', 'Não exceder limite em categoria'), ('GOAL_PROGRESS', 'Progredir em meta específica'), ('SAVINGS_INCREASE', 'Aumentar poupança'), ('CONSISTENCY', 'Manter consistência/streak')], default='SNAPSHOT', help_text='Tipo de validação que determina como o progresso é calculado', max_length=30),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='baseline_category_spending',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasto médio na categoria antes da missão começar', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='baseline_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Número de dias usados para calcular baseline'),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, help_text='Dias consecutivos atuais atendendo critério'),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='days_met_criteria',
            field=models.PositiveIntegerField(default=0, help_text='Total de dias que atendeu critério (não necessariamente consecutivos)'),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='days_violated_criteria',
            field=models.PositiveIntegerField(default=0, help_text='Total de dias que violou critério'),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='initial_goal_progress',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% de progresso da meta quando missão começou', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='initial_savings_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total em poupança quando missão começou', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='last_violation_date',
            field=models.DateField(blank=True, help_text='Data da última violação de critério', null=True),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='max_streak',
            field=models.PositiveIntegerField(default=0, help_text='Maior streak alcançado nesta missão'),
        ),
        migrations.AddField(
            model_name='missionprogress',
            name='validation_details',
            field=models.JSONField(default=dict, help_text='Detalhes de como validação está sendo feita'),
        ),
        migrations.AddField(
            model_name='usermonthlysnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdailysnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionprogresssnapshot',
            name='mission_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='finance.missionprogress'),
        ),
        migrations.AlterUniqueTogether(
            name='usermonthlysnapshot',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='userdailysnapshot',
            index=models.Index(fields=['user', '-snapshot_date'], name='finance_use_user_id_430b68_idx'),
        ),
        migrations.AddIndex(
            model_name='userdailysnapshot',
            index=models.Index(fields=['snapshot_date'], name='finance_use_snapsho_5e983c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdailysnapshot',
            unique_together={('user', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='missionprogresssnapshot',
            index=models.Index(fields=['mission_progress', 'snapshot_date'], name='finance_mis_mission_dbca37_idx'),
        ),
        migrations.AddIndex(
            model_name='missionprogresssnapshot',
            index=models.Index(fields=['snapshot_date'], name='finance_mis_snapsho_c3b81f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionprogresssnapshot',
            unique_together={('mission_progress', 'snapshot_date')},
        ),
    ]
