# Generated by Django 4.2.25 on 2025-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_add_snapshot_models_and_mission_enhancements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cached_total_debt',
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('REGULAR_INCOME', 'Renda principal'), ('EXTRA_INCOME', 'Renda extra'), ('SAVINGS', 'Poupança / Reserva'), ('INVESTMENT', 'Investimentos'), ('ESSENTIAL_EXPENSE', 'Despesas essenciais'), ('LIFESTYLE_EXPENSE', 'Estilo de vida'), ('GOAL', 'Metas e sonhos'), ('OTHER', 'Outros')], default='OTHER', max_length=24),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], db_index=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='transactionlink',
            name='link_type',
            field=models.CharField(choices=[('EXPENSE_PAYMENT', 'Pagamento de despesa'), ('INTERNAL_TRANSFER', 'Transferência interna'), ('SAVINGS_ALLOCATION', 'Alocação para poupança')], default='EXPENSE_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_rdr',
            field=models.PositiveIntegerField(default=35, help_text='meta de despesas recorrentes/renda em %'),
        ),
    ]
