# Generated by Django 4.2.25 on 2025-11-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_remove_debt_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('SAVINGS', 'Juntar Dinheiro'), ('CATEGORY_EXPENSE', 'Reduzir Gastos'), ('CATEGORY_INCOME', 'Aumentar Receita'), ('CUSTOM', 'Personalizada')], default='CUSTOM', help_text='Tipo da meta', max_length=20),
        ),
    ]
