# Generated by Django 4.2.25 on 2025-11-11 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0040_category_allow_null_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_DEACTIVATED', 'Usuário Desativado'), ('USER_REACTIVATED', 'Usuário Reativado'), ('XP_ADJUSTED', 'XP Ajustado'), ('LEVEL_ADJUSTED', 'Nível Ajustado'), ('PROFILE_UPDATED', 'Perfil Atualizado'), ('MISSIONS_RESET', 'Missões Resetadas'), ('TRANSACTIONS_DELETED', 'Transações Deletadas'), ('OTHER', 'Outro')], help_text='Tipo de ação realizada', max_length=30)),
                ('old_value', models.TextField(blank=True, help_text='Valor anterior (JSON se necessário)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Novo valor (JSON se necessário)', null=True)),
                ('reason', models.TextField(blank=True, help_text='Motivo/justificativa da ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do administrador', null=True)),
                ('admin_user', models.ForeignKey(help_text='Administrador que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='Usuário que recebeu a ação', on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Ação Administrativa',
                'verbose_name_plural': 'Logs de Ações Administrativas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='finance_adm_timesta_99055d_idx'), models.Index(fields=['target_user', '-timestamp'], name='finance_adm_target__a4ba93_idx'), models.Index(fields=['admin_user', '-timestamp'], name='finance_adm_admin_u_8d9daf_idx'), models.Index(fields=['action_type', '-timestamp'], name='finance_adm_action__40bdb7_idx')],
            },
        ),
    ]
