# Generated by Django 4.2.26 on 2025-11-11 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0041_admin_action_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da conquista', max_length=200)),
                ('description', models.TextField(help_text='Descrição detalhada da conquista')),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financeiro'), ('SOCIAL', 'Social'), ('MISSION', 'Missões'), ('STREAK', 'Sequência'), ('GENERAL', 'Geral')], default='GENERAL', help_text='Categoria da conquista', max_length=20)),
                ('tier', models.CharField(choices=[('BEGINNER', 'Iniciante'), ('INTERMEDIATE', 'Intermediário'), ('ADVANCED', 'Avançado')], default='BEGINNER', help_text='Nível de dificuldade', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=50, help_text='Recompensa em XP ao desbloquear')),
                ('icon', models.CharField(default='🏆', help_text='Emoji ou ícone da conquista', max_length=50)),
                ('criteria', models.JSONField(default=dict, help_text="Critérios para desbloquear (ex: {'transactions': 10, 'type': 'count'})")),
                ('is_active', models.BooleanField(default=True, help_text='Conquista ativa no sistema')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Conquista gerada por IA')),
                ('priority', models.PositiveIntegerField(default=50, help_text='Prioridade de exibição (1-100, menor = maior prioridade)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-xp_reward', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False, help_text='Conquista desbloqueada')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progresso atual (ex: 5 de 10 transações)')),
                ('progress_max', models.PositiveIntegerField(default=100, help_text='Progresso máximo necessário')),
                ('unlocked_at', models.DateTimeField(blank=True, help_text='Data e hora do desbloqueio', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='finance.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['category', 'tier'], name='finance_ach_categor_054bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['is_active', 'priority'], name='finance_ach_is_acti_69ba8f_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'is_unlocked'], name='finance_use_user_id_0a45be_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement', 'is_unlocked'], name='finance_use_achieve_f9639d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
