# Generated by Django 4.2.26 on 2025-11-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_populate_mission_impacts_tips'),
        ('finance', '0042_achievement_userachievement_and_more'),
    ]

    operations = [
    ]
