# Generated by Django 4.2.26 on 2025-11-13 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0043_merge_20251112_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='generation_context',
            field=models.JSONField(blank=True, default=dict, help_text='Contexto de geração automática (dados usados para criar a missão)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_system_generated',
            field=models.BooleanField(default=False, help_text='Se a missão foi gerada automaticamente pelo sistema'),
        ),
        migrations.AddField(
            model_name='mission',
            name='min_payments_count',
            field=models.PositiveIntegerField(blank=True, help_text='Número mínimo de pagamentos a serem rastreados', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='min_transaction_frequency',
            field=models.PositiveIntegerField(blank=True, help_text='Frequência mínima de transações por semana (para missões de consistência)', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='requires_payment_tracking',
            field=models.BooleanField(default=False, help_text='Se a missão requer rastreamento de pagamentos (campo is_paid nas transações)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_categories',
            field=models.ManyToManyField(blank=True, help_text='Categorias alvo para missões que envolvem múltiplas categorias', related_name='target_missions', to='finance.category'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_goals',
            field=models.ManyToManyField(blank=True, help_text='Metas alvo para missões que envolvem múltiplas metas', related_name='target_missions', to='finance.goal'),
        ),
        migrations.AddField(
            model_name='mission',
            name='transaction_type_filter',
            field=models.CharField(choices=[('ALL', 'Todas'), ('INCOME', 'Receitas'), ('EXPENSE', 'Despesas'), ('TRANSFER', 'Transferências')], default='ALL', help_text='Tipo de transação a ser considerado na validação', max_length=10),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('ONBOARDING_TRANSACTIONS', 'Primeiros passos: Transações'), ('ONBOARDING_CATEGORIES', 'Primeiros passos: Categorias'), ('ONBOARDING_GOALS', 'Primeiros passos: Metas'), ('TPS_IMPROVEMENT', 'Aumentar poupança (TPS)'), ('RDR_REDUCTION', 'Reduzir dívidas (RDR)'), ('ILI_BUILDING', 'Construir reserva (ILI)'), ('CATEGORY_REDUCTION', 'Reduzir gastos em categoria'), ('CATEGORY_SPENDING_LIMIT', 'Manter limite de categoria'), ('CATEGORY_ELIMINATION', 'Eliminar gastos supérfluos'), ('GOAL_ACHIEVEMENT', 'Completar meta'), ('GOAL_CONSISTENCY', 'Contribuir regularmente'), ('GOAL_ACCELERATION', 'Acelerar progresso de meta'), ('SAVINGS_STREAK', 'Sequência de poupança'), ('EXPENSE_CONTROL', 'Controlar gastos mensais'), ('INCOME_TRACKING', 'Registrar receitas'), ('PAYMENT_DISCIPLINE', 'Pagar contas em dia'), ('FINANCIAL_HEALTH', 'Saúde financeira completa'), ('WEALTH_BUILDING', 'Construção de patrimônio')], default='ONBOARDING_TRANSACTIONS', help_text='Tipo de missão que determina quando será aplicada', max_length=30),
        ),
        migrations.AlterField(
            model_name='mission',
            name='validation_type',
            field=models.CharField(choices=[('SNAPSHOT', 'Comparação inicial vs atual'), ('TEMPORAL', 'Manter critério por período'), ('CATEGORY_REDUCTION', 'Reduzir X% em categoria'), ('CATEGORY_LIMIT', 'Não exceder R$ em categoria'), ('CATEGORY_ZERO', 'Zero gastos em categoria'), ('GOAL_PROGRESS', 'Atingir X% de progresso'), ('GOAL_CONTRIBUTION', 'Contribuir R$ para meta'), ('GOAL_COMPLETION', 'Completar meta 100%'), ('TRANSACTION_COUNT', 'Registrar X transações'), ('TRANSACTION_CONSISTENCY', 'X transações/semana'), ('PAYMENT_COUNT', 'Registrar X pagamentos'), ('INDICATOR_THRESHOLD', 'Atingir valor de indicador'), ('INDICATOR_IMPROVEMENT', 'Melhorar indicador em X%'), ('INDICATOR_MAINTENANCE', 'Manter indicador por X dias'), ('MULTI_CRITERIA', 'Múltiplos critérios simultâneos')], default='TRANSACTION_COUNT', help_text='Tipo de validação que determina como o progresso é calculado', max_length=35),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionlink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False),
        ),
    ]
