# Generated by Django 4.2.26 on 2025-11-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_make_category_user_required'),
        ('finance', '0044_refactor_mission_system_sprint1'),
    ]

    operations = [
    ]
