# Generated by Django 4.2.26 on 2025-11-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0045_merge_20251113_1518'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='cat_user_type_sys_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='Categoria padrão do sistema (criada automaticamente para novos usuários)'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='finance_cat_user_id_0d1be8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'is_system_default'], name='finance_cat_user_id_e0ad5c_idx'),
        ),
    ]
