# Generated by Django 4.2.26 on 2025-11-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0046_remove_category_cat_user_type_sys_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='validation_type',
            field=models.CharField(choices=[('SNAPSHOT', 'Comparação inicial vs atual'), ('TEMPORAL', 'Manter critério por período'), ('CATEGORY_REDUCTION', 'Reduzir X% em categoria'), ('CATEGORY_LIMIT', 'Não exceder R$ em categoria'), ('CATEGORY_ZERO', 'Zero gastos em categoria'), ('GOAL_PROGRESS', 'Atingir X% de progresso'), ('GOAL_CONTRIBUTION', 'Contribuir R$ para meta'), ('GOAL_COMPLETION', 'Completar meta 100%'), ('TRANSACTION_COUNT', 'Registrar X transações'), ('TRANSACTION_CONSISTENCY', 'X transações/semana'), ('PAYMENT_COUNT', 'Registrar X pagamentos'), ('INDICATOR_THRESHOLD', 'Atingir valor de indicador'), ('INDICATOR_IMPROVEMENT', 'Melhorar indicador em X%'), ('INDICATOR_MAINTENANCE', 'Manter indicador por X dias'), ('SAVINGS_INCREASE', 'Aumentar poupança'), ('CONSISTENCY', 'Manter consistência/streak'), ('MULTI_CRITERIA', 'Múltiplos critérios simultâneos')], default='TRANSACTION_COUNT', help_text='Tipo de validação que determina como o progresso é calculado', max_length=35),
        ),
    ]
