# Generated by Django 4.2.26 on 2025-11-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0041_simplify_goal_model'),
        ('finance', '0047_add_legacy_validation_choices'),
    ]

    operations = [
    ]
