# Generated by Django 4.2.26 on 2025-11-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_merge_20251123_1940'),
    ]

    operations = [
        # Remove UserDailySnapshot
        migrations.DeleteModel(
            name='UserDailySnapshot',
        ),
        # Remove UserMonthlySnapshot
        migrations.DeleteModel(
            name='UserMonthlySnapshot',
        ),
        # Remove MissionProgressSnapshot
        migrations.DeleteModel(
            name='MissionProgressSnapshot',
        ),
    ]
