# Generated by Django 4.2.26 on 2025-11-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0050_simplify_mission_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('-created_at',), 'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ('priority', 'title'), 'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
        migrations.AlterModelOptions(
            name='missionprogress',
            options={'ordering': ('mission__priority', 'mission__title'), 'verbose_name': 'Progresso de Missão', 'verbose_name_plural': 'Progressos de Missões'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date', '-created_at'), 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterModelOptions(
            name='transactionlink',
            options={'ordering': ('-created_at',), 'verbose_name': 'Vínculo de Transação', 'verbose_name_plural': 'Vínculos de Transações'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='xptransaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'Transação de XP', 'verbose_name_plural': 'Transações de XP'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('SAVINGS', 'Juntar Dinheiro'), ('EXPENSE_REDUCTION', 'Reduzir Gastos'), ('INCOME_INCREASE', 'Aumentar Receita'), ('EMERGENCY_FUND', 'Fundo de Emergência'), ('CUSTOM', 'Personalizada')], default='CUSTOM', help_text='Tipo da meta', max_length=20),
        ),
    ]
