# Generated by Django 4.2.26 on 2025-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0051_add_goal_types'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(
                fields=['user', 'type', 'date'],
                name='tx_user_type_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(
                fields=['user', 'is_recurring', '-date'],
                name='tx_user_rec_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(
                fields=['user', 'category', '-date'],
                name='tx_user_cat_date_idx'
            ),
        ),
    ]
