# Generated by Django 4.2.26 on 2025-12-01 12:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0052_add_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                to='finance.category',
                related_name='goals_targeting_this',
                help_text='Categoria alvo para metas de redução de gastos'
            ),
        ),
        migrations.AddField(
            model_name='goal',
            name='baseline_amount',
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                blank=True,
                null=True,
                help_text='Valor de referência inicial (gasto/receita mensal antes da meta)'
            ),
        ),
        migrations.AddField(
            model_name='goal',
            name='tracking_period_months',
            field=models.PositiveIntegerField(
                default=3,
                help_text='Período em meses para cálculo de progresso (padrão: 3 meses)'
            ),
        ),
    ]
