# Generated by Django 4.2.26 on 2025-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0053_add_goal_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='tx_user_type_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tx_user_rec_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tx_user_cat_date_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionprogress',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('FAILED', 'Não Concluída')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'deleted_at'], name='finance_tra_user_id_9468a1_idx'),
        ),
    ]
