# Generated by Django 4.2.26 on 2025-12-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0057_remove_emergency_fund_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='goal_progress_target',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='target_goal',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='target_goals',
        ),
        migrations.RemoveField(
            model_name='missionprogress',
            name='initial_goal_progress',
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('ONBOARDING', 'Primeiros Passos'), ('TPS_IMPROVEMENT', 'Aumentar Poupança (TPS)'), ('RDR_REDUCTION', 'Reduzir Gastos Recorrentes (RDR)'), ('ILI_BUILDING', 'Construir Reserva (ILI)'), ('CATEGORY_REDUCTION', 'Reduzir Gastos em Categoria')], default='ONBOARDING', help_text='Tipo de missão que determina quando será aplicada', max_length=30),
        ),
        migrations.AlterField(
            model_name='mission',
            name='validation_type',
            field=models.CharField(choices=[('TRANSACTION_COUNT', 'Registrar X Transações'), ('INDICATOR_THRESHOLD', 'Atingir Valor de Indicador'), ('CATEGORY_REDUCTION', 'Reduzir % em Categoria'), ('TEMPORAL', 'Manter Critério por Período')], default='TRANSACTION_COUNT', help_text='Tipo de validação que determina como o progresso é calculado', max_length=35),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
