# Generated by Django 4.2.25 on 2025-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0059_simplify_mission_validation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionprogress',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('FAILED', 'Não Concluída'), ('SKIPPED', 'Pulada')], default='PENDING', max_length=10),
        ),
    ]
